2024-09-25 17:06:39,900 | tests_12_4 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\GOBLIN\Desktop\PycharmProjectForUniver\Модуль №12. Поддержка цикла разработки\Домашнее задание по теме Логирование\tests_12_4.py", line 79, in test_run
    runner_2 = Runner(876)
               ^^^^^^^^^^^
  File "C:\Users\GOBLIN\Desktop\PycharmProjectForUniver\Модуль №12. Поддержка цикла разработки\Домашнее задание по теме Логирование\tests_12_4.py", line 12, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-09-25 17:06:39,900 | tests_12_4 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\GOBLIN\Desktop\PycharmProjectForUniver\Модуль №12. Поддержка цикла разработки\Домашнее задание по теме Логирование\tests_12_4.py", line 67, in test_walk
    runner_1 = Runner('Den',speed=-5)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GOBLIN\Desktop\PycharmProjectForUniver\Модуль №12. Поддержка цикла разработки\Домашнее задание по теме Логирование\tests_12_4.py", line 17, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
